name: Deploy Node.js Application

on:
  push:
    branches:
      - main # Trigger the workflow on push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22" # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Deploy to Server via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Create SSH directory and add SSH private key
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Configure SSH to avoid host key checking
          echo "Host 192.168.1.100" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config

          # Create the target directory on the server if it does not exist
          ssh deployuser@192.168.1.100 "mkdir -p /var/www/myapp"

          # Sync the local repository to the target directory on the server
          rsync -avz --delete-after ./ deployuser@192.168.1.100:/var/www/myapp

          # Restart the server if needed (optional)
          ssh deployuser@192.168.1.100 "pm2 restart myapp || pm2 start /var/www/myapp/app.js --name 'myapp'"
